name = "gg-pixel-server"
main = "src/index.ts"
compatibility_date = "2025-01-15"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "gg-pixel"
database_id = "48159819-71c5-4b3c-9ead-0dade50ada33"
migrations_dir = "migrations"
